In [2]:
import pandas as pd
import numpy as np
import os
import ast
from PIL import Image

In [4]:
ruta_df = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\data\df_final1.csv"
df = pd.read_csv(ruta_df)
df.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road

In [5]:
### SOLO LAS IAMGENES ESCOGIDAS EN EL EXPERIMENTO
# 50f5eb66fdc9f065f000828e: 50f5eb5ffdc9f065f00081fc
# 50f5eaf0fdc9f065f0007e7e: 50f5ead5fdc9f065f0007dc1
image_ids = ['50f5ea5bfdc9f065f0007ab6',
 '50f5ea5bfdc9f065f0007ab9',
 '50f5ea5cfdc9f065f0007abf',
 '50f5ea5cfdc9f065f0007ac5',
 '50f5ea5dfdc9f065f0007ada',
 '50f5ea5ffdc9f065f0007b06',
 '50f5ea60fdc9f065f0007b19',
 '50f5ea61fdc9f065f0007b1d',
 '50f5ea61fdc9f065f0007b1f',
 '50f5ea61fdc9f065f0007b22',
 '50f5ea61fdc9f065f0007b27',
 '50f5eaa5fdc9f065f0007b7b',
 '50f5eaa5fdc9f065f0007b7c',
 '50f5eaa5fdc9f065f0007b81',
 '50f5eaa6fdc9f065f0007b8f',
 '50f5eaa6fdc9f065f0007b94',
 '50f5eaa7fdc9f065f0007ba0',
 '50f5eaa7fdc9f065f0007ba4',
 '50f5eaa9fdc9f065f0007bc7',
 '50f5eac6fdc9f065f0007ca1',
 '50f5eac6fdc9f065f0007cab',
 '50f5eac7fdc9f065f0007cb2',
 '50f5eacafdc9f065f0007cfd',
 '50f5eacbfdc9f065f0007d01',
 '50f5ead3fdc9f065f0007d9f',
 '50f5ead3fdc9f065f0007da4',
 '50f5ead3fdc9f065f0007da9',
 '50f5ead4fdc9f065f0007daa',
 '50f5ead4fdc9f065f0007db2',
 '50f5ead5fdc9f065f0007dbe',
 '50f5ead5fdc9f065f0007dbf',
 '50f5ead5fdc9f065f0007dc2',
 '50f5ead5fdc9f065f0007dc7',
 '50f5ead5fdc9f065f0007dca',
 '50f5ead5fdc9f065f0007dcb',
 '50f5ead6fdc9f065f0007dcd',
 '50f5ead6fdc9f065f0007dcf',
 '50f5ead6fdc9f065f0007dd8',
 '50f5eae9fdc9f065f0007dea',
 '50f5eaeafdc9f065f0007e08',
 '50f5eaecfdc9f065f0007e2c',
 '50f5eaecfdc9f065f0007e2d',
 '50f5eaecfdc9f065f0007e2f',
 '50f5eaecfdc9f065f0007e30',
 '50f5eaecfdc9f065f0007e36',
 '50f5eaedfdc9f065f0007e40',
 '50f5eaedfdc9f065f0007e46',
 '50f5eaedfdc9f065f0007e4b',
 '50f5eaeefdc9f065f0007e50',
 '50f5eaeefdc9f065f0007e55',
 '50f5eaeefdc9f065f0007e58',
 '50f5eaeefdc9f065f0007e59',
 '50f5eaeefdc9f065f0007e5a',
 '50f5eaeefdc9f065f0007e5e',
 '50f5eaeffdc9f065f0007e5f',
 '50f5eaeffdc9f065f0007e68',
 '50f5ead5fdc9f065f0007dc1',
 '50f5eaf0fdc9f065f0007e81',
 '50f5eaf0fdc9f065f0007e82',
 '50f5eaf1fdc9f065f0007e84',
 '50f5eaf1fdc9f065f0007e86',
 '50f5eaf1fdc9f065f0007e87',
 '50f5eaf1fdc9f065f0007e88',
 '50f5eaf1fdc9f065f0007e8b',
 '50f5eaf1fdc9f065f0007e8c',
 '50f5eaf1fdc9f065f0007e8f',
 '50f5eaf1fdc9f065f0007e91',
 '50f5eaf2fdc9f065f0007e99',
 '50f5eaf2fdc9f065f0007e9c',
 '50f5eaf2fdc9f065f0007e9d',
 '50f5eaf2fdc9f065f0007ea1',
 '50f5eaf2fdc9f065f0007ea2',
 '50f5eaf2fdc9f065f0007ea6',
 '50f5eaf3fdc9f065f0007eac',
 '50f5eaf3fdc9f065f0007eae',
 '50f5eaf3fdc9f065f0007eb6',
 '50f5eaf3fdc9f065f0007eb8',
 '50f5eaf3fdc9f065f0007ebe',
 '50f5eaf3fdc9f065f0007ec1',
 '50f5eaf4fdc9f065f0007ec5',
 '50f5eaf4fdc9f065f0007ec6',
 '50f5eaf4fdc9f065f0007ecd',
 '50f5eaf4fdc9f065f0007ed1',
 '50f5eaf4fdc9f065f0007ed3',
 '50f5eaf4fdc9f065f0007ed4',
 '50f5eaf6fdc9f065f0007efd',
 '50f5eaf9fdc9f065f0007f25',
 '50f5eb16fdc9f065f0007f48',
 '50f5eb23fdc9f065f000802e',
 '50f5eb25fdc9f065f0008060',
 '50f5eb26fdc9f065f0008074',
 '50f5eb27fdc9f065f0008083',
 '50f5eb43fdc9f065f0008140',
 '50f5eb5ffdc9f065f00081fe',
 '50f5eb5ffdc9f065f0008200',
 '50f5eb5ffdc9f065f0008203',
 '50f5eb60fdc9f065f000820c',
 '50f5eb60fdc9f065f0008211',
 '50f5eb60fdc9f065f0008216',
 '50f5eb60fdc9f065f0008219',
 '50f5eb61fdc9f065f0008224',
 '50f5eb61fdc9f065f000822b',
 '50f5eb62fdc9f065f0008237',
 '50f5eb62fdc9f065f0008244',
 '50f5eb63fdc9f065f0008245',
 '50f5eb63fdc9f065f0008248',
 '50f5eb63fdc9f065f000824f',
 '50f5eb63fdc9f065f0008253',
 '50f5eb63fdc9f065f0008258',
 '50f5eb64fdc9f065f0008265',
 '50f5eb64fdc9f065f0008267',
 '50f5eb64fdc9f065f0008268',
 '50f5eb64fdc9f065f000826c',
 '50f5eb64fdc9f065f000826d',
 '50f5eb65fdc9f065f0008273',
 '50f5eb66fdc9f065f0008286',
 '50f5eb66fdc9f065f000828d',
 '50f5eb5ffdc9f065f00081fc',
 '50f5eb67fdc9f065f0008294',
 '50f5eb67fdc9f065f0008298',
 '50f5eb67fdc9f065f000829f',
 '50f5eb68fdc9f065f00082a3',
 '50f5eb68fdc9f065f00082a7',
 '50f5eb68fdc9f065f00082ae',
 '50f5eb68fdc9f065f00082b0',
 '50f5eb69fdc9f065f00082bb',
 '50f5eb69fdc9f065f00082bc',
 '50f5eb69fdc9f065f00082c0',
 '50f5eb69fdc9f065f00082c9',
 '50f5eb69fdc9f065f00082cc',
 '50f5eb69fdc9f065f00082cd',
 '50f5eb6afdc9f065f00082d4',
 '50f5eb6afdc9f065f00082d5',
 '50f5eb6afdc9f065f00082d9',
 '50f5eb6afdc9f065f00082df',
 '50f5eb6afdc9f065f00082e1',
 '50f5eb6afdc9f065f00082e2',
 '50f5ebc6fdc9f065f00084ea',
 '50f5ebcafdc9f065f0008548',
 '50f5ebcbfdc9f065f000855e',
 '50f5ebd2fdc9f065f00085e6',
 '50f5ebd2fdc9f065f00085ed',
 '50f5ebd2fdc9f065f00085f0',
 '50f5ec0dfdc9f065f0008647',
 '50f5ec0efdc9f065f0008658',
 '50f5ec17fdc9f065f0008708',
 '50f5ec18fdc9f065f0008719',
 '50f5ec1ffdc9f065f00087a4',
 '50f5ec37fdc9f065f0008802',
 '50f5ec40fdc9f065f00088bc']

In [ ]:
import pandas as pd
import os
import shutil

# 1. Tu lista de IDs del experimento


# 2. Creamos el DataFrame de mapeo (0 a 149)
contador = list(range(0, len(image_ids)))
df = pd.DataFrame({
    'Contador': contador,
    'ID': image_ids
})

# =========================================================================
# 3. RUTAS DE ORIGEN: ¿Dónde están los archivos con los nombres largos?
# (¡Ajusta estas rutas a las carpetas correctas en tu PC!)
# =========================================================================

# carpeta_origen_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\ade20k_group_ratios\ratios"
# carpeta_origen_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\ade20k_group_masks\masks"

carpeta_origen_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\DISORDER_ratio\ratios"
carpeta_origen_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\DISORDER_mask\masks"

# =========================================================================
# 4. RUTAS DE DESTINO: ¿Dónde quieres guardar los archivos renombrados?
# (El script creará automáticamente las carpetas si no existen)
# =========================================================================
carpeta_destino_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Disorder\csv"
carpeta_destino_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Disorder\pkl"
# carpeta_destino_img = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\images" # Opcional

# Crear carpetas si no existen
os.makedirs(carpeta_destino_csv, exist_ok=True)
os.makedirs(carpeta_destino_pkl, exist_ok=True)
# os.makedirs(carpeta_destino_img, exist_ok=True) # Opcional

print(f"Iniciando el renombrado de {len(image_ids)} elementos...\n")

Iniciando el renombrado de 150 elementos...

In [14]:
archivos_copiados = 0
archivos_faltantes = 0

# 5. Iterar sobre el DataFrame y copiar/renombrar
for index, row in df.iterrows():
    id_original = row['ID']
    nuevo_nombre = str(row['Contador'])
    
    # Construir las rutas exactas de los archivos originales
    origen_csv = os.path.join(carpeta_origen_csv, f"{id_original}.csv")
    origen_pkl = os.path.join(carpeta_origen_pkl, f"{id_original}.pkl")
    # origen_img = os.path.join(carpeta_origen_img, f"{id_original}.png") # O .jpg dependiendo de tu dataset
    
    # Construir las nuevas rutas (con números de 0 a 149)
    destino_csv = os.path.join(carpeta_destino_csv, f"{nuevo_nombre}.csv")
    destino_pkl = os.path.join(carpeta_destino_pkl, f"{nuevo_nombre}.pkl")
    # destino_img = os.path.join(carpeta_destino_img, f"{nuevo_nombre}.png")
    
    # Mover y renombrar CSV
    if os.path.exists(origen_csv):
        shutil.copy2(origen_csv, destino_csv) # Usamos copy2 para mantener la metadata del archivo
        archivos_copiados += 1
    else:
        print(f"  [ERROR] No se encontró el CSV original: {id_original}.csv")
        archivos_faltantes += 1
        
    # Mover y renombrar PKL
    if os.path.exists(origen_pkl):
        shutil.copy2(origen_pkl, destino_pkl)
        archivos_copiados += 1
    else:
        print(f"  [ERROR] No se encontró el PKL original: {id_original}.pkl")
        archivos_faltantes += 1

    # Mover y renombrar Imágenes (Descomentar si es necesario)
    # if os.path.exists(origen_img):
    #     shutil.copy2(origen_img, destino_img)

print(f"\n¡Proceso completado!")
print(f"Archivos copiados exitosamente: {archivos_copiados}")
if archivos_faltantes > 0:
    print(f"ATENCIÓN: Faltaron {archivos_faltantes} archivos. Revisa las rutas de origen.")

¡Proceso completado!
Archivos copiados exitosamente: 300

In [73]:
import joblib
import pandas as pd
import os

# Ajusta estas rutas a donde tienes tu archivo 0.pkl y 0.csv
archivo_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\pkl\0.pkl"
archivo_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\csv\0.csv"

print("--- ANALIZANDO ARCHIVO .PKL ---")
if os.path.exists(archivo_pkl):
    # Cargamos la matriz matemática
    matriz_pkl = joblib.load(archivo_pkl)
    
    # .shape nos devuelve (alto, ancho)
    alto, ancho = matriz_pkl.shape
    print(f"Resolución exacta de la máscara: {ancho} píxeles de ancho x {alto} píxeles de alto.")
    print(f"Formato nativo de la matriz: {matriz_pkl.shape}")
else:
    print("No se encontró el archivo PKL.")

print("\n--- ANALIZANDO ARCHIVO .CSV ---")
if os.path.exists(archivo_csv):
    # Cargamos el dataframe (separado por punto y coma)
    df_csv = pd.read_csv(archivo_csv, sep=';')
    
    # .shape en Pandas nos devuelve (filas, columnas)
    filas, columnas = df_csv.shape
    print(f"Dimensiones de la tabla: {filas} filas (clases detectadas) y {columnas} columnas (atributos).")
else:
    print("No se encontró el archivo CSV.")

--- ANALIZANDO ARCHIVO .PKL ---
Resolución exacta de la máscara: 400 píxeles de ancho x 300 píxeles de alto.
Formato nativo de la matriz: (300, 400)

--- ANALIZANDO ARCHIVO .CSV ---
Dimensiones de la tabla: 8 filas (clases detectadas) y 5 columnas (atributos).

In [1]:
import pandas as pd
import numpy as np
import os
import joblib

def actualizar_df_grouped_por_imagename():
    # 1. Rutas exactas a tus archivos
    ruta_df = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\data\df_final1.csv"
    carpeta_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\csv"
    carpeta_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\pkl"

    print("1. Cargando el dataset original...")
    df = pd.read_csv(ruta_df)

    print("2. Inicializando datos Grouped limpios (ADE20K queda intacto)...")
    df["class_id_grouped"] = "unknown"
    df["main_class_grouped"] = "unknown"
    df["hex_color_grouped"] = "#999999"
    df["class_ratio_grouped"] = 0.0

    FRONTEND_W = 800.0
    FRONTEND_H = 600.0

    # =======================================================
    # LA CLAVE: Iteramos por ImageName, igual que tu script de ADE20K
    # =======================================================
    nombres_unicos = df["ImageName"].dropna().unique()
    print(f"3. Procesando {len(nombres_unicos)} imágenes basadas en ImageName...")

    for i, img_name in enumerate(nombres_unicos):
        
        # Formatear el nombre para que coincida con el archivo (ej. de 3.0 a "3")
        try:
            img_name_val = int(img_name)
        except:
            img_name_val = str(img_name).strip()
            
        archivo_pkl = os.path.join(carpeta_pkl, f"{img_name_val}.pkl")
        archivo_csv = os.path.join(carpeta_csv, f"{img_name_val}.csv")

        if not os.path.exists(archivo_pkl) or not os.path.exists(archivo_csv):
            if i % 10 == 0:
                print(f"   [!] Faltan archivos para ImageName {img_name_val}, saltando...")
            continue

        if i % 10 == 0:
            print(f"   Cruzando datos para ImageName: {img_name_val}.pkl ...")

        try:
            # A. Leer el diccionario (csv)
            df_ratios = pd.read_csv(archivo_csv, sep=';')
            color_map = {}
            for _, row in df_ratios.iterrows():
                try:
                    c_id = int(float(row['group_class_id']))
                    grupo = str(row['group_name']).strip().lower()
                    ratio_str = str(row['ratio']).replace(',', '.')
                    ratio = float(ratio_str) / 100.0 if float(ratio_str) > 1 else float(ratio_str)
                    hex_val = str(row['hex_color']).strip()
                    color_map[c_id] = {'group_name': grupo, 'ratio': ratio, 'hex': hex_val}
                except: pass
            
            # B. Leer la matriz PKL
            segmentation_array = joblib.load(archivo_pkl)
            img_h, img_w = segmentation_array.shape

            # =======================================================
            # FILTRAMOS POR ImageName (El error estaba aquí antes)
            # =======================================================
            mascara_img = df["ImageName"] == img_name
            indices_gaze = df[mascara_img].index
            
            for idx in indices_gaze:
                if pd.isna(df.loc[idx, "pixelX"]) or pd.isna(df.loc[idx, "pixelY"]):
                    continue
                
                px_orig = float(df.loc[idx, "pixelX"])
                py_orig = float(df.loc[idx, "pixelY"])

                # Validamos que el punto no salga de la pantalla
                if px_orig < 0 or px_orig > FRONTEND_W or py_orig < 0 or py_orig > FRONTEND_H:
                    continue  

                # # =======================================================
                # # ESCALADO EXACTAMENTE IGUAL A ADE20K (Sin invertir ejes)
                # # =======================================================
                # x_pkl = int((px_orig * img_w) / FRONTEND_W)
                # y_pkl = int((py_orig * img_h) / FRONTEND_H)

                # =======================================================
                # ESCALADO CON INVERSIÓN DEL EJE Y (600 - Y)
                # =======================================================
                x_pkl = int((px_orig * img_w) / FRONTEND_W)
                y_pkl = int(((FRONTEND_H - py_orig) * img_h) / FRONTEND_H)

                x_pkl = min(x_pkl, img_w - 1)
                y_pkl = min(y_pkl, img_h - 1)
                
                class_id_pixel = int(segmentation_array[y_pkl, x_pkl])
                
                # Solo inyectamos los datos nuevos en las columnas Grouped
                if class_id_pixel in color_map:
                    datos = color_map[class_id_pixel]
                    df.loc[idx, "class_id_grouped"] = datos['group_name']
                    df.loc[idx, "main_class_grouped"] = datos['group_name']
                    df.loc[idx, "class_ratio_grouped"] = datos['ratio']
                    df.loc[idx, "hex_color_grouped"] = datos['hex']

        except Exception as e:
            print(f"Error procesando ImageName {img_name_val}: {e}")

    print("\n4. Guardando los cambios en df_final1.csv...")
    df.to_csv(ruta_df, index=False)
    print("¡ÉXITO! Tu Scarf Plot de Grouped ahora usará las imágenes correctas.")

if __name__ == "__main__":
    actualizar_df_grouped_por_imagename()

1. Cargando el dataset original...
2. Inicializando datos Grouped limpios (ADE20K queda intacto)...
3. Procesando 150 imágenes basadas en ImageName...
   Cruzando datos para ImageName: 3.pkl ...
   Cruzando datos para ImageName: 39.pkl ...
   Cruzando datos para ImageName: 63.pkl ...
   Cruzando datos para ImageName: 88.pkl ...
   Cruzando datos para ImageName: 124.pkl ...
   Cruzando datos para ImageName: 0.pkl ...
   Cruzando datos para ImageName: 26.pkl ...
   Cruzando datos para ImageName: 72.pkl ...
   Cruzando datos para ImageName: 108.pkl ...
   Cruzando datos para ImageName: 13.pkl ...
   Cruzando datos para ImageName: 94.pkl ...
   Cruzando datos para ImageName: 136.pkl ...
   Cruzando datos para ImageName: 62.pkl ...
   Cruzando datos para ImageName: 16.pkl ...
   Cruzando datos para ImageName: 6.pkl ...

4. Guardando los cambios en df_final1.csv...
¡ÉXITO! Tu Scarf Plot de Grouped ahora usará las imágenes correctas.

In [82]:
df1.isnull().sum()

Time                    0
ImageIndex              0
ImageName               0
X                       0
Y                       0
Z                       0
participante            0
pixelX                  0
pixelY                  0
class_id               13
class_name             13
ratio                  13
hex_color              13
main_class             13
class_id_grouped        0
class_ratio_grouped     0
hex_color_grouped       0
main_class_grouped      0
dtype: int64

In [2]:
df1 = pd.read_csv("df_final1.csv")

In [3]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_ratio_grouped,hex_color_grouped,main_class_grouped,class_id_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road,0.345942,#8C8C8C,floor,floor
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road,0.345942,#8C8C8C,floor,floor
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road,0.345942,#8C8C8C,floor,floor
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road,0.345942,#8C8C8C,floor,floor
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road,0.345942,#8C8C8C,floor,floor

In [120]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_ratio_grouped,hex_color_grouped,main_class_grouped,class_id_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road,0.331492,#04C803,vegetation,vegetation
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road,0.331492,#04C803,vegetation,vegetation
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road,0.331492,#04C803,vegetation,vegetation
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road,0.331492,#04C803,vegetation,vegetation
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road,0.331492,#04C803,vegetation,vegetation

In [117]:
df1#.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_ratio_grouped,hex_color_grouped,main_class_grouped,class_id_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.6150,#8C8C8C,road,0.396158,#B47878,construction,construction
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.6150,#8C8C8C,road,0.396158,#B47878,construction,construction
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.6150,#8C8C8C,road,0.396158,#B47878,construction,construction
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.6150,#8C8C8C,road,0.396158,#B47878,construction,construction
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.6150,#8C8C8C,road,0.396158,#B47878,construction,construction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869595,1004.571,49,149,0.0034,1.0953,1.9938,30,403.4,295.3,7.0,road;route,15.7817,#8C8C8C,road,0.111233,#04C803,vegetation,vegetation
869596,1004.605,49,149,0.0064,1.0952,1.9939,30,406.4,295.2,2.0,building;edifice,19.0542,#B47878,building,0.111233,#04C803,vegetation,vegetation
869597,1004.637,49,149,0.0093,1.0954,1.9939,30,409.3,295.4,2.0,building;edifice,19.0542,#B47878,building,0.111233,#04C803,vegetation,vegetation
869598,1004.671,49,149,0.0122,1.0956,1.9940,30,412.2,295.6,2.0,building;edifice,19.0542,#B47878,building,0.111233,#04C803,vegetation,vegetation
869599,1004.706,49,149,0.0152,1.0955,1.9941,30,415.2,295.5,2.0,building;edifice,19.0542,#B47878,building,0.111233,#04C803,vegetation,vegetation

In [89]:
df1.columns

Index(['Time', 'ImageIndex', 'ImageName', 'X', 'Y', 'Z', 'participante',
       'pixelX', 'pixelY', 'class_id', 'class_name', 'ratio', 'hex_color',
       'main_class', 'class_id_grouped', 'class_ratio_grouped',
       'hex_color_grouped', 'main_class_grouped'],
      dtype='object')

In [104]:
df1.memory_usage(deep=True).sum() / (1024 * 1024)

87.56647872924805

In [95]:
df1.memory_usage(deep=True).sum() / (1024 * 1024)

367.43074893951416

In [96]:
df1.columns

Index(['Time', 'ImageIndex', 'ImageName', 'X', 'Y', 'Z', 'participante',
       'pixelX', 'pixelY', 'class_id', 'class_name', 'ratio', 'hex_color',
       'main_class', 'class_id_grouped', 'class_ratio_grouped',
       'hex_color_grouped', 'main_class_grouped'],
      dtype='object')

In [97]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_id_grouped,class_ratio_grouped,hex_color_grouped,main_class_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road,sky,0.323958,#06E6E6,sky
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road,sky,0.323958,#06E6E6,sky
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road,sky,0.323958,#06E6E6,sky
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road,sky,0.323958,#06E6E6,sky
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road,sky,0.323958,#06E6E6,sky

In [100]:
df1["class_id"].unique()

array([  7.,   5.,  12.,   2.,  33.,  21.,  13.,  73.,  10.,  18.,   1.,
        22.,  14.,  39.,  30.,  69.,   3., 103.,  15., 123., 105.,  54.,
        88.,  70., 116.,  81.,  94.,  41.,  44.,  84.,  42.,  17.,  87.,
         9., 117.,  26., 124., 129.,  62.,  16.,  nan,  53., 126., 128.,
       139.,  96., 137.,  43., 122., 101.,   4.,  27., 106.,  85.,  35.])

In [112]:
# 1. FLOATS → float32
float_cols = ["Time", "X", "Y", "Z", "pixelX", "pixelY", "ratio", "class_ratio_grouped"]
df1[float_cols] = df1[float_cols].astype("float32")

# 2. REDONDEAR
df1[float_cols] = df1[float_cols].round(4)

# 3. ENTEROS → optimizar
df1["ImageIndex"] = df1["ImageIndex"].astype("int32")
df1["participante"] = df1["participante"].astype("int16")
#df1["class_id"] = df1["class_id"].astype("Int8")
# 1. Reemplazar infinitos (por seguridad)
df1["class_id"] = df1["class_id"].replace([np.inf, -np.inf], np.nan)

# 2. Convertir a entero "flexible" primero (Int64)
df1["class_id"] = df1["class_id"].astype("Int64")

# 3. Luego bajar a Int8
df1["class_id"] = df1["class_id"].astype("Int8")

#df1["class_id_grouped"] = df1["class_id_grouped"].astype("Int8")

# 4. STRINGS → category
cat_cols = [
    "ImageName", "class_name", "hex_color", "main_class",
    "hex_color_grouped", "main_class_grouped"
]
df1[cat_cols] = df1[cat_cols].astype("category")

# 5. GUARDAR (recomendado)
#df1.to_csv("data_optimized.csv.gz", index=False, compression="gzip")

In [113]:
del df1["class_id_grouped"]

In [114]:
df1.to_csv("df_final1.csv", index=False)

In [105]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_id_grouped,class_ratio_grouped,hex_color_grouped,main_class_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.200012,204.600006,7,road;route,29.615,#8C8C8C,road,sky,0.324,#06E6E6,sky
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.200012,206.000000,7,road;route,29.615,#8C8C8C,road,sky,0.324,#06E6E6,sky
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.299988,207.000000,7,road;route,29.615,#8C8C8C,road,sky,0.324,#06E6E6,sky
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.399994,207.000000,7,road;route,29.615,#8C8C8C,road,sky,0.324,#06E6E6,sky
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.600006,205.899994,7,road;route,29.615,#8C8C8C,road,sky,0.324,#06E6E6,sky

In [107]:
del df1["class_id_grouped"]

In [84]:
df1["pixelX"].max(), df1["pixelX"].min()

(800.7, -0.8000000000000114)

In [85]:
df1["pixelY"].max(), df1["pixelY"].min()

(596.8999999999999, 5.599999999999909)

In [63]:
import pandas as pd
import os
import glob

# Ruta a tu carpeta de CSVs agrupados
carpeta_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\csv"

# Un 'set' automáticamente ignora los duplicados
todos_los_grupos = set()

# Buscar todos los archivos .csv en esa carpeta
archivos_csv = glob.glob(os.path.join(carpeta_csv, "*.csv"))

print(f"Analizando {len(archivos_csv)} archivos...")

for archivo in archivos_csv:
    try:
        # Leemos cada csv
        df_temp = pd.read_csv(archivo, sep=';')
        
        # Si tiene la columna group_name, extraemos sus valores únicos
        if 'group_name' in df_temp.columns:
            grupos_en_imagen = df_temp['group_name'].dropna().unique()
            todos_los_grupos.update(grupos_en_imagen)
    except Exception as e:
        print(f"Error leyendo {archivo}: {e}")

# Convertimos a una lista ordenada alfabéticamente
lista_final = sorted(list(todos_los_grupos))

print(f"\n¡Listo! Se encontraron {len(lista_final)} grupos únicos en total:")
for grupo in lista_final:
    print(f"- {grupo}")

Analizando 150 archivos...

¡Listo! Se encontraron 13 grupos únicos en total:
- body_water
- city_elements
- clothes_object
- construction
- floor
- human
- indoor_object
- miscellaneous
- nature_object
- outdoor_object
- sky
- terrain_vehicle
- vegetation

In [72]:
df1["main_class_grouped"].unique()

array(['unknown', 'construction', 'sky', 'vegetation', 'floor',
       'indoor_object', 'miscellaneous', 'terrain_vehicle', 'body_water',
       'human', 'clothes_object', 'city_elements', 'nature_object',
       'outdoor_object'], dtype=object)

In [71]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_id_grouped,class_ratio_grouped,hex_color_grouped,main_class_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road,unknown,0.0,#999999,unknown
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road,unknown,0.0,#999999,unknown
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road,unknown,0.0,#999999,unknown
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road,unknown,0.0,#999999,unknown
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road,unknown,0.0,#999999,unknown

In [24]:
df1.head()

,Time,ImageIndex,ImageName,X,Y,Z,participante,pixelX,pixelY,class_id,class_name,ratio,hex_color,main_class,class_id_grouped,class_ratio_grouped,hex_color_grouped,main_class_grouped
0,7.984,0,3,0.0052,1.0046,1.9762,1,405.2,204.6,7.0,road;route,29.615,#8C8C8C,road,7.0,29.615,#8C8C8C,road
1,8.017,0,3,0.0052,1.0060,1.9764,1,405.2,206.0,7.0,road;route,29.615,#8C8C8C,road,7.0,29.615,#8C8C8C,road
2,8.052,0,3,0.0053,1.0070,1.9766,1,405.3,207.0,7.0,road;route,29.615,#8C8C8C,road,7.0,29.615,#8C8C8C,road
3,8.084,0,3,0.0054,1.0070,1.9768,1,405.4,207.0,7.0,road;route,29.615,#8C8C8C,road,7.0,29.615,#8C8C8C,road
4,8.117,0,3,0.0056,1.0059,1.9766,1,405.6,205.9,7.0,road;route,29.615,#8C8C8C,road,7.0,29.615,#8C8C8C,road

In [59]:
df1["class_id"] == df1["class_id_grouped"]
son_iguales = df1["class_id"].equals(df1["class_id_grouped"])
print(f"¿S iguales?: {son_iguales}")

¿S iguales?: False

In [56]:
df1["main_class"] == df1["main_class_grouped"]
son_iguales = df1["main_class"].equals(df1["main_class_grouped"])
print(f"¿S iguales?: {son_iguales}")

¿S iguales?: False

In [ ]:
# carpeta_csv = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\csv"
# carpeta_pkl = r"C:\Users\vdela\Desktop\UrbanGazeVis\static\images\images\Grouped\pkl"

### ADE20K DISORDER CLASSES